server:
  port: 9001
spring:
  application:
    name: hrm-management
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm_manage
    username: root
    password: 0..123456
mybatis-plus:
  mapper-locations: classpath:com/yzw/mapper/*Mapper.xml
  type-aliases-package: com.yzw.domain,com.yzw.query

